[font]
size = 14.0
builtin_box_drawing = true

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
padding = { x = 15, y = 15 }
decorations = "buttonless"
option_as_alt = "Both"

[cursor]
style = { shape = "Block", blinking = "On" }

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[scrolling]
history = 5000

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\n"
